services:
  web:
    tty: true
    stdin_open: true
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/code/
    command: bash -c "rm -rf /code/tmp/pids/server.pid &&
                      bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./tmp/db:/lib/var/postgresql/data
    environment:
      POSTGRES_PASSWORD: password